# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Aaditya Verma
title: SDE III - Innovation, Fidelity International
email: aadityaverma1998@gmail.com
# email_title: Email (Email title override)
phone: +91 9582906389
# phone_title: Phone (Phone title override)
website: https://aaditya420.github.io/
# website_title: Web (Website title override)

# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username: aaditya420
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: jekyll
linkedin_username: aadityaverma
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# orcid_username: 0000-0000-0000-0000
# googlescholar_username: D847cGsAAAAJ

# Additional icon links
additional_links:
- title: An automated approach to public distribution system using IoT (Research Paper)
  icon: fa-book
  url: https://pdf.sciencedirectassets.com/280203/1-s2.0-S1877050918X00088/1-s2.0-S1877050918309128/main.pdf?X-Amz-Security-Token=IQoJb3JpZ2luX2VjELX%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMSJHMEUCICaDPdZLybo3WPmPpPLyOC5y2JWm37GKqaCWO5%2BlbnzhAiEAk9T2Ew9e2qwl5r1mUXcfPa5oEUL3LHFzibPlQBKk9MIqswUIHhAFGgwwNTkwMDM1NDY4NjUiDEfnyo0HOzmt8d5%2BQiqQBTc4uygI5unsXUh12nxHB7WQYhHkdxRCN1qFl6mds9KTv4tXbtpfX00l932pPBsPsSTX8YBWMUXhuJC9%2FkwevLnY4TifznY3J%2FXnUpx1ZCkYI%2FrB3KsY5r%2Fg8ARrW8zRXUl2WLZ7ZzX25pVYWTCfMk8aD2ccVZ%2BJfvTo8VLd1zqOSX6znNKEME8V3COdBruoYKw74ENqknxO%2F%2FAg4lt8ployhaqc0yU64x0sazIu06vDwGqSXiiloqrVX0POBSnGTDMrhzHllNu%2F9xm1Ar8TgJ7p4LKqo2rCW9uKteJv1i3lbZ9ohd3MxWtZDoL3sE7RY7huaEV9wugv0RyN3EDFCDz49BvA7YNucFmBIukTIcGKRRxw2Oon2sT%2B4QRqceY11Xo0L9TlEb8CAG4WmX2mw9LJkiW0sMw4dI9ZsISi%2FjKg4idUcXuz%2BUaj3pFio%2B1y%2Bm1jN32Q5LqeYHwP0kC9%2FTgPU51Qid20Ze0sFh8pQ%2FKGiltrJzgLB%2BuF4ByGyjvHqyUlgBMotJB%2BiM03H%2Fy3ByXFApUfuHaRtGyiNe3fo3uodkH3FdEC5YW9Q8gTLfmzHXT2DUNuFBAwduCsKsJvzhvt3GTLDBe%2ByhvjhJ5prRqSEKQC%2FmQn%2FaMpz2UUJ4PrGJwJQsQQm%2BKKNtwIdvOtyy0o5rr%2FZknDj6N3VdYbWqbvVlnAPdZkUjaYgfbTI7nC9B86a0Mq0GfPm%2FMy2ybCY%2FeeXqfWpSZgZoWPv0VhH9DzhvOokSG9ulQELqK%2BBAkTARUtXrdPGlrwI31aTwvwzVf3io2fdf1ML4kQ9j5RKH8qWP7siGUz55MPj4KpXomsqKz4L%2B14%2FHlwMa4OrxWihFFjaFOgeB4fI2NT4qF4m2WnMMuMqasGOrEBc2Wro5Xy0A%2Fc313sYkUGTd%2F28s9neJNWjh0LtMtEus6Wbvj0lvzVLqfag%2BHPQNWoeafhnC635mNMgAxJ8dMEiAUv%2Bacu%2BtDEI22Gwz9AAEa7Twy9CjATEhdfDLLgYmkuO4RkTUiDpdiRRNzPF7Bu1lPhHuH6TK7e2F7%2BUY8guBdzVwDIUqZtPXiuZrV3a8IzyH%2BYtsUIokr3w7KOo44vhhU3HFNcLSmm%2BkYLW4%2FjeG%2FO&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20231201T214258Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAQ3PHCVTY3H3X6I45%2F20231201%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Signature=70ae56907d2946889fbd554052c6ccf70040b14b84814e77673c7d9383cc9b73&hash=5e95d3d164d073843591341b50c62845a0cfceb3d48f3988751dbb53d6af3ea5&host=68042c943591013ac2b2430a89b270f6af2c76d8dfd086a07176afe7c76c2c61&pii=S1877050918309128&tid=spdf-ae93e4f4-7bea-402f-98e7-c447958f8d92&sid=63f10e068462e54fec8a09e2ff2bcc016f8egxrqb&type=client&tsoh=d3d3LnNjaWVuY2VkaXJlY3QuY29t&ua=0f01585d04015b5700&rr=82ee80c24bea072f&cc=in
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: |
    Experienced Software Engineer specializing in Generative AI and Large Language Models (LLMs), with a strong background in full-stack development, automation, and data management. Proven track record in driving AI innovation and implementing advanced AI solutions to enhance organizational growth. Adept at leading cross-functional teams and delivering complex projects on time.

content:
  - title: Projects
    layout: list
    content:
      - layout: left
        title: GAI based application for RRT Operations
        description: | 
          Implemented GAI based application into production for RRT Operations team end to end using Terraform, AWS, React stack. Reduced workload by 75% enabling them to serve multiple advisors.

      - layout: left
        title: FILBrowserGPT
        description: | 
          Implemented first ever chrome based extension FILBrowserGPT to production enabling use of organization GPT solution on web browsers. Potential savings of up to 2000 hours every week.

      - layout: left
        title: GAI based solution for Client Services
        description: | 
          Implemented GAI based solution for Client Services team to analyze call transcripts on various Fidelity based frameworks and guidelines. Potential savings of $784k annually.

      - layout: left
        title: RRT GPT solution for Operations
        description: | 
          Secured first position in the Improve-a-thon internal hackathon event, implementing RRT GPT solution for Operations team within time bound limits. Used internal GAI solution for analyzing and transforming manual notes to timeline based summary.

      - layout: left
        title: Inner Source AWS modules
        description: | 
          Contributed in fixing critical bugs on Inner Source AWS modules.

      - layout: left
        title: FILxGPT
        description: | 
          Responsible for development of FILxGPT an internal GPT solution for Fidelity. Potential savings of 2000+ hours daily for FIL Employees and Developers.

      - layout: left
        title: GAI based application for Client Services
        description: | 
          Implemented GAI based application to Production for Client Services team, enabling them to respond to Client’s Secure Messages with the help of GAI. Saving 50% of their time collating and preparing the responses.

      - layout: left
        title: GAI based application for PI Clients
        description: | 
          Developed GAI based application for PI Clients, enabling the clients to be able to chat on their portfolio data.

      - layout: left
        title: Knowledge Graph for CoSec team
        description: | 
          Implemented Knowledge Graph based solution to MVP for CoSec team, enabling collation of Legal Entity data and efficient querying on top of it using AWS Neptune for Graph Database, Terraform for IaC, Python for the backend and React for UI.

      - layout: left
        title: Fine tuning open source LLM models
        description: | 
          Implemented and Researched on fine tuning open source LLM models with specific dataset. Tuned Falcon 7B model with Fintech data for comparing offerings across the board and how FIL can improve their own.

      - layout: left
        title: Speech-to-Image application
        description: | 
          Developed a Speech-to-Image application for showcasing GAI use cases in Long Services Awards event using Whisper and Stable Diffusion models.

      - layout: left
        title: Knowledge Graph for IVR
        description: | 
          Implemented first ever Knowledge Graph based application to MVP for retrieving most relevant search results for the clients speaking over IVR on their fund data queries. Utilized AWS Neptune in LPD configuration and Terraform for Iac. Potential savings of over $140k annually.

      - layout: left
        title: Automation for Fund Data Management
        description: | 
          Implemented automation for the Fund Data Management team on the Corporate Actions workflow. Utilizing spaCy to train NER models and extract entity based data from PDF files. Potential savings of $120k annually.

      - layout: left
        title: Charts Repository
        description: | 
          Achieved first position in Data Games, internal hackathon event, developing a Charts Repository for the Research team saving them 20% time in creating and retrieving various market research charts data.

      - layout: left
        title: Blockchain based rewards application
        description: | 
          Implemented blockchain based rewards application for FIL internal employees using ERC-20 protocol.

      - layout: left
        title: FIODE database
        description: | 
          Responsible for development and maintenance of FIODE database. Implemented and Updated PL/SQL procedures, improving data loading speeds by 20%.

      - layout: left
        title: Automated data flow
        description: | 
          Automated data flow using python scripts & Control-M jobs, saving 50% in manual efforts.

      - layout: left
        title: Fund Launches and Data Migration
        description: | 
          Supported critical implementations for Fund Launches and Data Migration activities.

      - layout: left
        title: Insights application for Central European marketing team
        description: | 
          Implemented Insights application for Central European marketing team. Collating live news and sentiment data across various platforms like Twitter, Ignites Europe, etc., on Fidelity competitors. Enabling the marketing team to make critical decisions based on the insights.

      - layout: left
        title: LinkedIN based Insights tool
        description: | 
          Implemented LinkedIN based Insights tool for the HR team, enabling them to visualize the influx and outflux of employees. Potential savings in the form of competitive advantage.

      - layout: left
        title: Network Scanning tool
        description: | 
          Responsible for implementing a Network Scanning tool using Django framework, scanning across 650k ports to check for unauthorized access.

      - layout: left
        title: Reporting framework using MongoDB
        description: | 
          Implemented reporting framework using MongoDB for auto scanning and storage of reports and alerts.

  - title: Experience
    layout: list
    content:
      - layout: right
        title: Fidelity International
        sub_title: Senior Analyst Programmer
        caption: Aug 2023 - Present
        description: | 
          Implemented GAI based application into production for RRT Operations team end to end using Terraform, AWS, React stack. Reduced workload by 75% enabling them to serve multiple advisors. Implemented first ever chrome based extension FILBrowserGPT to production enabling use of organization GPT solution on web browsers. Potential savings of up to 2000 hours every week. Implemented GAI based solution for Client Services team to analyze call transcripts on various Fidelity based frameworks and guidelines. Potential savings of $784k annually. Secured first position in the Improve-a-thon internal hackathon event, implementing RRT GPT solution for Operations team within time bound limits. Used internal GAI solution for analyzing and transforming manual notes to timeline based summary. Contributed in fixing critical bugs on Inner Source AWS modules.

      - layout: right
        title: Fidelity International
        sub_title: Analyst Programmer
        caption: Aug 2022 - July 2023
        description: | 
          Responsible for development of FILxGPT an internal GPT solution for Fidelity. Potential savings of 2000+ hours daily for FIL Employees and Developers. Implemented GAI based application to Production for Client Services team, enabling them to respond to Client’s Secure Messages with the help of GAI. Saving 50% of their time collating and preparing the responses. Developed GAI based application for PI Clients, enabling the clients to be able to chat on their portfolio data. Implemented Knowledge Graph based solution to MVP for CoSec team, enabling collation of Legal Entity data and efficient querying on top of it using AWS Neptune for Graph Database, Terraform for IaC, Python for the backend and React for UI. Implemented and Researched on fine tuning open source LLM models with specific dataset. Tuned Falcon 7B model with Fintech data for comparing offerings across the board and how FIL can improve their own. Developed a Speech-to-Image application for showcasing GAI use cases in Long Services Awards event using Whisper and Stable Diffusion models.

      - layout: right
        title: Fidelity International
        sub_title: Programmer
        caption: Aug 2021 - July 2022
        description: | 
          Implemented first ever Knowledge Graph based application to MVP for retrieving most relevant search results for the clients speaking over IVR on their fund data queries. Utilized AWS Neptune in LPD configuration and Terraform for Iac. Potential savings of over $140k annually. Implemented automation for the Fund Data Management team on the Corporate Actions workflow. Utilizing spaCy to train NER models and extract entity based data from PDF files. Potential savings of $120k annually. Achieved first position in Data Games, internal hackathon event, developing a Charts Repository for the Research team saving them 20% time in creating and retrieving various market research charts data. Implemented blockchain based rewards application for FIL internal employees using ERC-20 protocol.

      - layout: right
        title: Fidelity International
        sub_title: Graduate Programmer
        caption: Aug 2020 - July 2021
        description: | 
          Responsible for development and maintenance of FIODE database. Implemented and Updated PL/SQL procedures, improving data loading speeds by 20%. Automated data flow using python scripts & Control-M jobs, saving 50% in manual efforts. Supported critical implementations for Fund Launches and Data Migration activities. Implemented Insights application for Central European marketing team. Collating live news and sentiment data across various platforms like Twitter, Ignites Europe, etc., on Fidelity competitors. Enabling the marketing team to make critical decisions based on the insights. Implemented LinkedIN based Insights tool for the HR team, enabling them to visualize the influx and outflux of employees. Potential savings in the form of competitive advantage.

      - layout: right
        title: RankWatch Inc.
        sub_title: Software Developer Intern
        caption: May 2019 - July 2019
        description: | 
          Responsible for implementing a Network Scanning tool using Django framework, scanning across 650k ports to check for unauthorized access. Implemented reporting framework using MongoDB for auto scanning and storage of reports and alerts.

  - title: Education
    layout: text
    content: |
      **The NorthCap University**  
      Bachelors in Technology Computer Science, July 2020
      - Secured third place in Smart India Hackathon 2019. Developed messaging solution for HUL Goods Delivery pipeline.
      - Part of Dean’s List for three consecutive years (9.5+CGPA).
      - Published Research paper under Elseviers publication identifying Automated approach to India’s PDS.

  - title: Skills
    layout: list
    content:
      - layout: left
        title: Programming Languages
        description: |
          Terraform, AWS, Python, Django, ReactJS, Solidity, SQL, PLSQL

      - layout: left
        title: Tools & Technologies
        description: |
          GAI, Jenkins, Git, Github Actions, Knowledge Graph, Docker, Kubernetes, Snowflake, MongoDB

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ".DS_Store/"
  ]
